[project]
name = "Uploadn_Chat_(Tabular_RAG)"
version = "0.1.0"
description = "Chat with CSV/XLSX using DF/SQL/RAG and local Ollama phi3"
requires-python = ">=3.10"
dependencies = []
authors = [
    { name = "Nilesh Gode", email = "nileshg6716@gmail.com" }
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 100

